version: '2'

services:
  getmail_dovecot:
    build:
      context: ./
      dockerfile: Dockerfile
    image: kevinflynn387/mailserver-dovecot:latest
    container_name: mailserver1
    volumes:
      - /srv/mail/home:/home
      - /srv/mail/cron.d:/etc/cron.d
      - /srv/mail/ssl:/etc/ssl/private:ro
    ports:
      - "143:143"  # imap
      - "993:993"  # imaps
      - "4190:4190"  # managesieve
    restart: unless-stopped